dist: trusty

language: php

env:
  global:
    - COMPOSER_ARGS="--ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"
    - DEPS="phpunit/phpunit squizlabs/php_codesniffer php-coveralls/php-coveralls"

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly

install:
  - composer install $COMPOSER_ARGS

before_script:
  - composer require $COMPOSER_ARGS $DEPS

script:
  - php vendor/bin/phpunit
  - php vendor/bin/phpcs

after_script:
  - if [ -f ./build/logs/clover.xml ]; then php vendor/bin/php-coveralls -v; fi
